spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xcstudy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml  #告诉springboot去哪找xml映射文件
